import asyncio
from motor.motor_asyncio import AsyncIOMotorClient
import os
from dotenv import load_dotenv

load_dotenv()

MONGO_URI = os.getenv("MONGO_URI", "mongodb://localhost:27017")
DB_NAME = os.getenv("DB_NAME", "ai_fashion")

PRODUCTS = [
    # ─── CASUAL ──────────────────────────────────────────────────
    {"name": "Classic White Cotton Tee", "outfit_type": "T-Shirt", "category": "Casual Wear", "price_range": "₹299–₹499", "price_label": "Budget", "purchase_link": "https://www.amazon.in/s?k=white+cotton+tee", "tags": ["casual", "white", "tshirt", "cotton", "everyday"], "image_url": "https://image.pollinations.ai/prompt/white%20cotton%20t-shirt%20fashion%20product%20photo%20white%20background?width=300&height=400&seed=1&nologo=true"},
    {"name": "Slim Fit Blue Denim Jeans", "outfit_type": "Jeans", "category": "Casual Wear", "price_range": "₹899–₹1,499", "price_label": "Budget", "purchase_link": "https://www.amazon.in/s?k=slim+fit+blue+jeans", "tags": ["casual", "denim", "blue", "jeans", "everyday", "streetwear"], "image_url": "https://image.pollinations.ai/prompt/slim%20fit%20blue%20denim%20jeans%20fashion%20product%20white%20background?width=300&height=400&seed=2&nologo=true"},
    {"name": "Striped Casual Shirt", "outfit_type": "Shirt", "category": "Casual Wear", "price_range": "₹599–₹999", "price_label": "Budget", "purchase_link": "https://www.amazon.in/s?k=striped+casual+shirt", "tags": ["casual", "stripes", "shirt", "cotton", "everyday"], "image_url": "https://image.pollinations.ai/prompt/striped%20casual%20shirt%20fashion%20product%20white%20background?width=300&height=400&seed=3&nologo=true"},
    {"name": "Relaxed Fit Cargo Pants", "outfit_type": "Pants", "category": "Streetwear", "price_range": "₹1,299–₹1,999", "price_label": "Mid-range", "purchase_link": "https://www.amazon.in/s?k=cargo+pants+men", "tags": ["streetwear", "cargo", "casual", "pants", "urban"], "image_url": "https://image.pollinations.ai/prompt/cargo%20pants%20streetwear%20fashion%20product%20white%20background?width=300&height=400&seed=4&nologo=true"},
    {"name": "Floral Summer Sundress", "outfit_type": "Dress", "category": "Casual Wear", "price_range": "₹799–₹1,299", "price_label": "Budget", "purchase_link": "https://www.amazon.in/s?k=floral+sundress+women", "tags": ["casual", "dress", "floral", "summer", "women", "colorful"], "image_url": "https://image.pollinations.ai/prompt/floral%20summer%20sundress%20fashion%20product%20white%20background?width=300&height=400&seed=5&nologo=true"},
    {"name": "Oversized Graphic Hoodie", "outfit_type": "Hoodie", "category": "Streetwear", "price_range": "₹1,099–₹1,799", "price_label": "Mid-range", "purchase_link": "https://www.amazon.in/s?k=oversized+graphic+hoodie", "tags": ["streetwear", "hoodie", "casual", "graphic", "oversized", "neon"], "image_url": "https://image.pollinations.ai/prompt/oversized%20graphic%20hoodie%20streetwear%20fashion%20product%20white%20background?width=300&height=400&seed=6&nologo=true"},
    {"name": "Linen Wide-Leg Trousers", "outfit_type": "Trousers", "category": "Casual Wear", "price_range": "₹1,199–₹1,899", "price_label": "Mid-range", "purchase_link": "https://www.amazon.in/s?k=linen+wide+leg+trousers", "tags": ["casual", "linen", "wide-leg", "minimalist", "summer", "women"], "image_url": "https://image.pollinations.ai/prompt/linen%20wide%20leg%20trousers%20fashion%20product%20white%20background?width=300&height=400&seed=7&nologo=true"},
    {"name": "Casual Polo T-Shirt", "outfit_type": "Polo", "category": "Casual Wear", "price_range": "₹499–₹899", "price_label": "Budget", "purchase_link": "https://www.amazon.in/s?k=polo+t-shirt+men", "tags": ["casual", "polo", "everyday", "men", "classic"], "image_url": "https://image.pollinations.ai/prompt/polo%20t-shirt%20fashion%20product%20white%20background?width=300&height=400&seed=8&nologo=true"},
    {"name": "Denim Jacket", "outfit_type": "Jacket", "category": "Casual Wear", "price_range": "₹1,499–₹2,499", "price_label": "Mid-range", "purchase_link": "https://www.amazon.in/s?k=denim+jacket+women", "tags": ["casual", "denim", "jacket", "everyday", "streetwear", "blue"], "image_url": "https://image.pollinations.ai/prompt/denim%20jacket%20fashion%20product%20white%20background?width=300&height=400&seed=9&nologo=true"},
    {"name": "Printed Co-ord Set", "outfit_type": "Co-ord Set", "category": "Casual Wear", "price_range": "₹1,599–₹2,299", "price_label": "Mid-range", "purchase_link": "https://www.amazon.in/s?k=printed+co+ord+set+women", "tags": ["casual", "coord", "matching", "printed", "women", "trendy"], "image_url": "https://image.pollinations.ai/prompt/printed%20co-ord%20set%20fashion%20product%20white%20background?width=300&height=400&seed=10&nologo=true"},

    # ─── FORMAL ──────────────────────────────────────────────────
    {"name": "Classic Black Formal Blazer", "outfit_type": "Blazer", "category": "Formal Wear", "price_range": "₹2,499–₹4,999", "price_label": "Mid-range", "purchase_link": "https://www.amazon.in/s?k=black+formal+blazer+women", "tags": ["formal", "black", "blazer", "office", "minimalist", "women"], "image_url": "https://image.pollinations.ai/prompt/black%20formal%20blazer%20fashion%20product%20white%20background?width=300&height=400&seed=11&nologo=true"},
    {"name": "Men's Navy Suit", "outfit_type": "Suit", "category": "Formal Wear", "price_range": "₹4,999–₹9,999", "price_label": "Mid-range", "purchase_link": "https://www.amazon.in/s?k=navy+suit+men", "tags": ["formal", "navy", "suit", "office", "men", "wedding"], "image_url": "https://image.pollinations.ai/prompt/navy%20suit%20men%20fashion%20product%20white%20background?width=300&height=400&seed=12&nologo=true"},
    {"name": "Formal Pencil Skirt", "outfit_type": "Skirt", "category": "Formal Wear", "price_range": "₹899–₹1,799", "price_label": "Mid-range", "purchase_link": "https://www.amazon.in/s?k=formal+pencil+skirt", "tags": ["formal", "skirt", "office", "women", "black", "minimalist"], "image_url": "https://image.pollinations.ai/prompt/formal%20pencil%20skirt%20fashion%20product%20white%20background?width=300&height=400&seed=13&nologo=true"},
    {"name": "White Oxford Formal Shirt", "outfit_type": "Shirt", "category": "Formal Wear", "price_range": "₹799–₹1,499", "price_label": "Budget", "purchase_link": "https://www.amazon.in/s?k=white+oxford+shirt+men", "tags": ["formal", "white", "shirt", "office", "men", "classic"], "image_url": "https://image.pollinations.ai/prompt/white%20oxford%20formal%20shirt%20fashion%20product%20white%20background?width=300&height=400&seed=14&nologo=true"},
    {"name": "Power Suit – Women", "outfit_type": "Pantsuit", "category": "Formal Wear", "price_range": "₹7,999–₹15,999", "price_label": "Premium", "purchase_link": "https://www.amazon.in/s?k=women+power+suit", "tags": ["formal", "suit", "office", "women", "power", "premium"], "image_url": "https://image.pollinations.ai/prompt/women%20power%20pantsuit%20fashion%20product%20white%20background?width=300&height=400&seed=15&nologo=true"},
    {"name": "Shift Dress – Office Style", "outfit_type": "Dress", "category": "Formal Wear", "price_range": "₹1,299–₹2,499", "price_label": "Mid-range", "purchase_link": "https://www.amazon.in/s?k=shift+dress+office+wear", "tags": ["formal", "dress", "office", "women", "minimalist", "black"], "image_url": "https://image.pollinations.ai/prompt/shift%20dress%20office%20wear%20fashion%20product%20white%20background?width=300&height=400&seed=16&nologo=true"},

    # ─── ETHNIC / FESTIVE ─────────────────────────────────────────
    {"name": "Banarasi Silk Saree – Red & Gold", "outfit_type": "Saree", "category": "Ethnic / Traditional", "price_range": "₹3,999–₹8,999", "price_label": "Mid-range", "purchase_link": "https://www.amazon.in/s?k=banarasi+silk+saree+red", "tags": ["ethnic", "saree", "silk", "wedding", "festive", "traditional", "red", "gold"], "image_url": "https://image.pollinations.ai/prompt/banarasi%20silk%20saree%20red%20gold%20fashion%20product%20white%20background?width=300&height=400&seed=17&nologo=true"},
    {"name": "Embroidered Lehenga Choli", "outfit_type": "Lehenga", "category": "Ethnic / Bridal", "price_range": "₹8,999–₹24,999", "price_label": "Premium", "purchase_link": "https://www.amazon.in/s?k=embroidered+lehenga+choli", "tags": ["ethnic", "lehenga", "wedding", "bridal", "embroidered", "silk", "festive"], "image_url": "https://image.pollinations.ai/prompt/embroidered%20lehenga%20choli%20bridal%20fashion%20product%20white%20background?width=300&height=400&seed=18&nologo=true"},
    {"name": "Anarkali Suit – Royal Blue", "outfit_type": "Anarkali", "category": "Ethnic / Traditional", "price_range": "₹2,499–₹5,999", "price_label": "Mid-range", "purchase_link": "https://www.amazon.in/s?k=anarkali+suit+blue", "tags": ["ethnic", "anarkali", "festive", "blue", "traditional", "women"], "image_url": "https://image.pollinations.ai/prompt/anarkali%20suit%20royal%20blue%20fashion%20product%20white%20background?width=300&height=400&seed=19&nologo=true"},
    {"name": "Kurta Pyjama Set – Men", "outfit_type": "Kurta Pyjama", "category": "Ethnic / Traditional", "price_range": "₹1,299–₹2,999", "price_label": "Mid-range", "purchase_link": "https://www.amazon.in/s?k=kurta+pyjama+set+men", "tags": ["ethnic", "kurta", "men", "festive", "traditional", "casual"], "image_url": "https://image.pollinations.ai/prompt/kurta%20pyjama%20set%20men%20fashion%20product%20white%20background?width=300&height=400&seed=20&nologo=true"},
    {"name": "Sherwani – Ivory Gold", "outfit_type": "Sherwani", "category": "Ethnic / Bridal Men", "price_range": "₹9,999–₹29,999", "price_label": "Premium", "purchase_link": "https://www.amazon.in/s?k=sherwani+men+ivory+gold", "tags": ["ethnic", "sherwani", "wedding", "men", "gold", "premium", "bridal"], "image_url": "https://image.pollinations.ai/prompt/sherwani%20ivory%20gold%20men%20fashion%20product%20white%20background?width=300&height=400&seed=21&nologo=true"},
    {"name": "Cotton Printed Kurti", "outfit_type": "Kurti", "category": "Ethnic Fusion", "price_range": "₹399–₹799", "price_label": "Budget", "purchase_link": "https://www.amazon.in/s?k=cotton+printed+kurti+women", "tags": ["ethnic", "kurti", "casual", "cotton", "women", "everyday", "kurthi"], "image_url": "https://image.pollinations.ai/prompt/cotton%20printed%20kurti%20women%20fashion%20product%20white%20background?width=300&height=400&seed=22&nologo=true"},
    {"name": "Indo-Western Dhoti Kurta Set", "outfit_type": "Dhoti Kurta", "category": "Ethnic Fusion", "price_range": "₹2,999–₹5,999", "price_label": "Mid-range", "purchase_link": "https://www.amazon.in/s?k=indo+western+dhoti+kurta", "tags": ["ethnic", "indo-western", "men", "dhoti", "festive", "wedding"], "image_url": "https://image.pollinations.ai/prompt/indo%20western%20dhoti%20kurta%20men%20fashion%20product%20white%20background?width=300&height=400&seed=23&nologo=true"},
    {"name": "Mirror Work Chaniya Choli", "outfit_type": "Chaniya Choli", "category": "Ethnic / Festive", "price_range": "₹3,499–₹7,999", "price_label": "Mid-range", "purchase_link": "https://www.amazon.in/s?k=mirror+work+chaniya+choli", "tags": ["ethnic", "festive", "chaniya", "choli", "garba", "colorful", "women"], "image_url": "https://image.pollinations.ai/prompt/mirror%20work%20chaniya%20choli%20fashion%20product%20white%20background?width=300&height=400&seed=24&nologo=true"},
    {"name": "Organza Saree – Pastel Pink", "outfit_type": "Saree", "category": "Ethnic / Traditional", "price_range": "₹2,499–₹5,499", "price_label": "Mid-range", "purchase_link": "https://www.amazon.in/s?k=organza+saree+pastel+pink", "tags": ["ethnic", "saree", "pastel", "pink", "festive", "women", "organza"], "image_url": "https://image.pollinations.ai/prompt/organza%20saree%20pastel%20pink%20fashion%20product%20white%20background?width=300&height=400&seed=25&nologo=true"},

    # ─── PARTY / EVENING ──────────────────────────────────────────
    {"name": "Sparkle Sequin Mini Dress", "outfit_type": "Party Dress", "category": "Party Wear", "price_range": "₹2,299–₹4,999", "price_label": "Mid-range", "purchase_link": "https://www.amazon.in/s?k=sequin+mini+dress+women", "tags": ["party", "sequin", "glam", "women", "night", "sparkle"], "image_url": "https://image.pollinations.ai/prompt/sparkle%20sequin%20mini%20dress%20fashion%20product%20white%20background?width=300&height=400&seed=26&nologo=true"},
    {"name": "Velvet Blazer – Emerald", "outfit_type": "Blazer", "category": "Party Wear", "price_range": "₹3,499–₹6,999", "price_label": "Mid-range", "purchase_link": "https://www.amazon.in/s?k=velvet+blazer+emerald+green", "tags": ["party", "velvet", "blazer", "green", "premium", "festive"], "image_url": "https://image.pollinations.ai/prompt/velvet%20blazer%20emerald%20green%20fashion%20product%20white%20background?width=300&height=400&seed=27&nologo=true"},
    {"name": "Satin Slip Dress – Champagne", "outfit_type": "Evening Dress", "category": "Evening Wear", "price_range": "₹2,999–₹5,999", "price_label": "Mid-range", "purchase_link": "https://www.amazon.in/s?k=satin+slip+dress+champagne", "tags": ["party", "satin", "dress", "evening", "champagne", "women"], "image_url": "https://image.pollinations.ai/prompt/satin%20slip%20dress%20champagne%20fashion%20product%20white%20background?width=300&height=400&seed=28&nologo=true"},
    {"name": "Jumpsuit – Black Party", "outfit_type": "Jumpsuit", "category": "Party Wear", "price_range": "₹1,999–₹3,999", "price_label": "Mid-range", "purchase_link": "https://www.amazon.in/s?k=black+party+jumpsuit+women", "tags": ["party", "jumpsuit", "black", "women", "night", "trendy"], "image_url": "https://image.pollinations.ai/prompt/black%20party%20jumpsuit%20fashion%20product%20white%20background?width=300&height=400&seed=29&nologo=true"},
    {"name": "Designer Bandage Dress", "outfit_type": "Party Dress", "category": "Party Wear", "price_range": "₹4,999–₹9,999", "price_label": "Premium", "purchase_link": "https://www.amazon.in/s?k=bandage+dress+women+party", "tags": ["party", "bandage", "dress", "premium", "women", "night"], "image_url": "https://image.pollinations.ai/prompt/bandage%20dress%20premium%20fashion%20product%20white%20background?width=300&height=400&seed=30&nologo=true"},

    # ─── STREETWEAR ───────────────────────────────────────────────
    {"name": "Neon Streetwear Jacket", "outfit_type": "Jacket", "category": "Streetwear", "price_range": "₹2,499–₹4,499", "price_label": "Mid-range", "purchase_link": "https://www.amazon.in/s?k=neon+streetwear+jacket", "tags": ["streetwear", "neon", "jacket", "urban", "youth", "bold"], "image_url": "https://image.pollinations.ai/prompt/neon%20streetwear%20jacket%20fashion%20product%20white%20background?width=300&height=400&seed=31&nologo=true"},
    {"name": "Baggy Track Pants", "outfit_type": "Track Pants", "category": "Streetwear", "price_range": "₹799–₹1,499", "price_label": "Budget", "purchase_link": "https://www.amazon.in/s?k=baggy+track+pants+men", "tags": ["streetwear", "track", "pants", "casual", "urban", "sporty"], "image_url": "https://image.pollinations.ai/prompt/baggy%20track%20pants%20streetwear%20fashion%20product%20white%20background?width=300&height=400&seed=32&nologo=true"},
    {"name": "Cropped Band Tee", "outfit_type": "T-Shirt", "category": "Streetwear", "price_range": "₹499–₹899", "price_label": "Budget", "purchase_link": "https://www.amazon.in/s?k=cropped+band+tee+women", "tags": ["streetwear", "crop", "tshirt", "women", "casual", "band"], "image_url": "https://image.pollinations.ai/prompt/cropped%20band%20tee%20streetwear%20fashion%20product%20white%20background?width=300&height=400&seed=33&nologo=true"},
    {"name": "Puffer Jacket – Black", "outfit_type": "Jacket", "category": "Winter Wear", "price_range": "₹1,999–₹3,999", "price_label": "Mid-range", "purchase_link": "https://www.amazon.in/s?k=puffer+jacket+black", "tags": ["winter", "jacket", "black", "warm", "streetwear", "casual"], "image_url": "https://image.pollinations.ai/prompt/black%20puffer%20jacket%20fashion%20product%20white%20background?width=300&height=400&seed=34&nologo=true"},
    {"name": "Graphic Sweatshirt – Vintage", "outfit_type": "Sweatshirt", "category": "Streetwear", "price_range": "₹799–₹1,599", "price_label": "Budget", "purchase_link": "https://www.amazon.in/s?k=graphic+sweatshirt+vintage", "tags": ["streetwear", "graphic", "sweatshirt", "casual", "vintage", "youth"], "image_url": "https://image.pollinations.ai/prompt/graphic%20vintage%20sweatshirt%20fashion%20product%20white%20background?width=300&height=400&seed=35&nologo=true"},

    # ─── ACTIVEWEAR ───────────────────────────────────────────────
    {"name": "Yoga Leggings – High Waist", "outfit_type": "Leggings", "category": "Activewear / Athleisure", "price_range": "₹699–₹1,299", "price_label": "Budget", "purchase_link": "https://www.amazon.in/s?k=high+waist+yoga+leggings", "tags": ["active", "sport", "yoga", "leggings", "women", "fitness"], "image_url": "https://image.pollinations.ai/prompt/high%20waist%20yoga%20leggings%20activewear%20fashion%20product%20white%20background?width=300&height=400&seed=36&nologo=true"},
    {"name": "Sports Bra & Shorts Set", "outfit_type": "Activewear Set", "category": "Activewear / Athleisure", "price_range": "₹999–₹1,999", "price_label": "Mid-range", "purchase_link": "https://www.amazon.in/s?k=sports+bra+shorts+set+women", "tags": ["active", "sport", "women", "gym", "fitness", "shorts"], "image_url": "https://image.pollinations.ai/prompt/sports%20bra%20shorts%20activewear%20fashion%20product%20white%20background?width=300&height=400&seed=37&nologo=true"},
    {"name": "Men's Gym T-Shirt – Dry Fit", "outfit_type": "T-Shirt", "category": "Activewear / Athleisure", "price_range": "₹399–₹799", "price_label": "Budget", "purchase_link": "https://www.amazon.in/s?k=dry+fit+gym+tshirt+men", "tags": ["active", "sport", "men", "gym", "dryfit", "fitness"], "image_url": "https://image.pollinations.ai/prompt/dry%20fit%20gym%20shirt%20activewear%20fashion%20product%20white%20background?width=300&height=400&seed=38&nologo=true"},

    # ─── PREMIUM / DESIGNER ───────────────────────────────────────
    {"name": "Premium Cashmere Wrap Coat", "outfit_type": "Coat", "category": "Winter Wear", "price_range": "₹12,999–₹29,999", "price_label": "Premium", "purchase_link": "https://www.amazon.in/s?k=cashmere+wrap+coat+women", "tags": ["premium", "winter", "cashmere", "coat", "women", "luxury"], "image_url": "https://image.pollinations.ai/prompt/cashmere%20wrap%20coat%20premium%20women%20fashion%20product%20white%20background?width=300&height=400&seed=39&nologo=true"},
    {"name": "Luxury Silk Blouse", "outfit_type": "Blouse", "category": "Formal Wear", "price_range": "₹5,999–₹12,999", "price_label": "Premium", "purchase_link": "https://www.amazon.in/s?k=luxury+silk+blouse+women", "tags": ["premium", "silk", "blouse", "formal", "women", "luxury"], "image_url": "https://image.pollinations.ai/prompt/luxury%20silk%20blouse%20women%20fashion%20product%20white%20background?width=300&height=400&seed=40&nologo=true"},
    {"name": "Designer Trench Coat", "outfit_type": "Trench Coat", "category": "Smart Casual / Formal", "price_range": "₹8,999–₹19,999", "price_label": "Premium", "purchase_link": "https://www.amazon.in/s?k=designer+trench+coat+women", "tags": ["premium", "trench", "coat", "formal", "women", "classic"], "image_url": "https://image.pollinations.ai/prompt/designer%20trench%20coat%20women%20fashion%20product%20white%20background?width=300&height=400&seed=41&nologo=true"},
    {"name": "Embellished Evening Gown", "outfit_type": "Gown", "category": "Evening Wear", "price_range": "₹14,999–₹39,999", "price_label": "Premium", "purchase_link": "https://www.amazon.in/s?k=embellished+evening+gown+women", "tags": ["premium", "gown", "evening", "women", "party", "embellished"], "image_url": "https://image.pollinations.ai/prompt/embellished%20evening%20gown%20premium%20fashion%20product%20white%20background?width=300&height=400&seed=42&nologo=true"},

    # ─── SUMMER / RESORT ──────────────────────────────────────────
    {"name": "Linen Beach Shirt – Men", "outfit_type": "Shirt", "category": "Summer / Resort Wear", "price_range": "₹799–₹1,499", "price_label": "Budget", "purchase_link": "https://www.amazon.in/s?k=linen+beach+shirt+men", "tags": ["summer", "beach", "linen", "men", "resort", "casual"], "image_url": "https://image.pollinations.ai/prompt/linen%20beach%20shirt%20men%20summer%20fashion%20product%20white%20background?width=300&height=400&seed=43&nologo=true"},
    {"name": "Maxi Boho Dress", "outfit_type": "Dress", "category": "Summer / Resort Wear", "price_range": "₹1,299–₹2,499", "price_label": "Mid-range", "purchase_link": "https://www.amazon.in/s?k=maxi+boho+dress+women", "tags": ["summer", "boho", "dress", "women", "maxi", "casual", "floral"], "image_url": "https://image.pollinations.ai/prompt/maxi%20boho%20dress%20women%20summer%20fashion%20product%20white%20background?width=300&height=400&seed=44&nologo=true"},
    {"name": "Tie-Dye Shorts & Tee Set", "outfit_type": "Shorts Set", "category": "Summer / Resort Wear", "price_range": "₹899–₹1,599", "price_label": "Budget", "purchase_link": "https://www.amazon.in/s?k=tie+dye+shorts+set", "tags": ["summer", "tie-dye", "shorts", "casual", "colorful", "beach"], "image_url": "https://image.pollinations.ai/prompt/tie%20dye%20shorts%20set%20summer%20fashion%20product%20white%20background?width=300&height=400&seed=45&nologo=true"},

    # ─── MINIMALIST ───────────────────────────────────────────────
    {"name": "Minimal White Linen Shirt", "outfit_type": "Shirt", "category": "Minimalist / Contemporary", "price_range": "₹1,299–₹2,499", "price_label": "Mid-range", "purchase_link": "https://www.amazon.in/s?k=white+linen+shirt+women", "tags": ["minimalist", "white", "linen", "shirt", "women", "office", "classic"], "image_url": "https://image.pollinations.ai/prompt/minimal%20white%20linen%20shirt%20fashion%20product%20white%20background?width=300&height=400&seed=46&nologo=true"},
    {"name": "Monochrome Midi Skirt", "outfit_type": "Skirt", "category": "Minimalist / Contemporary", "price_range": "₹999–₹1,999", "price_label": "Mid-range", "purchase_link": "https://www.amazon.in/s?k=monochrome+midi+skirt+women", "tags": ["minimalist", "midi", "skirt", "women", "black", "office"], "image_url": "https://image.pollinations.ai/prompt/monochrome%20midi%20skirt%20fashion%20product%20white%20background?width=300&height=400&seed=47&nologo=true"},
    {"name": "Neutral Toned Turtleneck", "outfit_type": "Top", "category": "Minimalist / Contemporary", "price_range": "₹799–₹1,599", "price_label": "Mid-range", "purchase_link": "https://www.amazon.in/s?k=neutral+turtleneck+women", "tags": ["minimalist", "turtleneck", "beige", "women", "casual", "winter"], "image_url": "https://image.pollinations.ai/prompt/neutral%20turtleneck%20top%20minimalist%20fashion%20product%20white%20background?width=300&height=400&seed=48&nologo=true"},
    {"name": "Straight-Cut Trousers – Beige", "outfit_type": "Trousers", "category": "Minimalist / Contemporary", "price_range": "₹1,199–₹2,299", "price_label": "Mid-range", "purchase_link": "https://www.amazon.in/s?k=beige+straight+trousers+women", "tags": ["minimalist", "trousers", "beige", "women", "office", "casual"], "image_url": "https://image.pollinations.ai/prompt/beige%20straight%20trousers%20minimalist%20fashion%20product%20white%20background?width=300&height=400&seed=49&nologo=true"},
    {"name": "Crisp Black Tuxedo – Men", "outfit_type": "Tuxedo", "category": "Formal Wear", "price_range": "₹9,999–₹24,999", "price_label": "Premium", "purchase_link": "https://www.amazon.in/s?k=black+tuxedo+men", "tags": ["premium", "formal", "tuxedo", "men", "black", "wedding", "night"], "image_url": "https://image.pollinations.ai/prompt/crisp%20black%20tuxedo%20men%20fashion%20product%20white%20background?width=300&height=400&seed=50&nologo=true"},
]


async def seed():
    client = AsyncIOMotorClient(MONGO_URI)
    db = client[DB_NAME]
    col = db["products"]

    existing = await col.count_documents({})
    if existing >= len(PRODUCTS):
        print(f"✅ Already have {existing} products in MongoDB. Skipping seed.")
        client.close()
        return

    await col.delete_many({})
    result = await col.insert_many(PRODUCTS)
    print(f"✅ Seeded {len(result.inserted_ids)} products to MongoDB '{DB_NAME}.products'")
    client.close()


if __name__ == "__main__":
    asyncio.run(seed())
